title:            煲仔饭
tagline:          慢慢品味
description:      Describe your website.
#Comment out url when working locally to resolve base urls correctly
url:

plugins:
  - jekyll-gist

# Owner/author information
owner:
  name:           ivoryxiong
  avatar:         xiong.jpg
  bio:            "TLM@PonyAI"
  email:          ivoryxiong@gmail.com
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  github: ivoryxiong
  linkedin:

# Analytics and webmaster tools stuff goes here
google_analytics: 'UA-34354303-1'
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in top navigation
# For external links add external: true
links:
  - title: 首页
    url: /
  - title: 归档
    url: /categories
  - title: 标签
    url: /tags
  - title: 关于
    url: /about
  - title: 百宝箱
    url: /toolbox

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:year/:month/:day/:title

# https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Asia/Hong_Kong
future:      true
pygments:    true
markdown:    kramdown
kramdown:
  extensions: [fenced_code_blocks]

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "minimal-mistakes.sublime-project", "minimal-mistakes.sublime-workspace"]
