title:            煲仔饭
tagline:          慢慢品味
description:      Describe your website.
#Comment out url when working locally to resolve base urls correctly
url:              http://127.0.0.1:4000

# Owner/author information
owner:
  name:           ivoryxiong
  avatar:         xiong.jpg
  bio:            "SDE@WUMII"
  email:          ivoryxiong@gmail.com
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  twitter:
  facebook:
  github: ivoryxiong
  linkedin:
  instagram:
  lastfm:
  tumblr:
  # For Google Authorship https://plus.google.com/authorship
  google_plus:  https://plus.google.com/100260282622512499798

# Analytics and webmaster tools stuff goes here
google_analytics: 'UA-34354303-1'
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in top navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Categories
    url: /categories
  - title: Tags
    url: /tags
  - title: About
    url: /about

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:year/:month/:day/:title

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Asia/Hong_Kong
future:      true
pygments:    true
markdown:    redcarpet
redcarpet:
  extensions: [fenced_code_blocks]

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "minimal-mistakes.sublime-project", "minimal-mistakes.sublime-workspace"]
